

services:
  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./models:/app/models  # Persist ML models
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    command: streamlit run src/dashboard/app.py
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # Enable persistence
    restart: unless-stopped


  # Redis Exporter for Prometheus metrics
  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

    # Prometheus for metrics
  prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus:/etc/prometheus
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      restart: unless-stopped

    # Grafana for visualization
  grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana_data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus
      restart: unless-stopped


volumes:
  redis_data:  # Persistent volume for Redis data
  prometheus_data:
  grafana_data:
